import Head from "next/head"
import Image from "next/image"

// import { checkout } from "../checkout"

export default function Home() {
  return (
    <div >
      <Head>
        <title>Physical NFTs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <h1 >Buy my physical NFTs</h1>
        <div >
          <div>
            <p>Very expensive art piece 1</p>
            {/* <button onClick={(() => {
              checkout({
                lineItems: [
                  {
                    price: "price_1KmmMDAFPWVcpdFFZWnMTT7Z",
                    quantity: 1
                  }
                ]
              })
            })}>BUY!</button> */}
          </div>
        </div>
      </main>
    </div>
  )
}